# Generated by Django 2.2.3 on 2019-10-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
